import{a as u,i,S as x}from"./assets/vendor-b0d10f48.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function p(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=p(r);fetch(r.href,s)}})();u.defaults.baseURL="https://pixabay.com/api/";async function f(t,e=1,p=15){try{return(await u.get("",{params:{key:"44946850-4c776fe0ffa968f959f660738",q:t,page:e,per_page:p,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(a){throw console.error("Fetch error: ",a),a}}function h(t){return t.map(e=>`<li class="gallery-list">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" title="${e.tags}">
        </a>
        <div >
          <ul class="text-list">
            <li class="text-item"><p class="text"><span class="text-span">Likes</span><span class="link-span">${e.likes}</span></p></li>
            <li class="text-item"><p class="text"><span class="text-span">Views</span><span class="link-span">${e.views}</span></p></li>
            <li class="text-item"><p class="text"><span class="text-span">Comments</span><span class="link-span">${e.comments}</span></p></li>
            <li class="text-item"><p class="text"><span class="text-span">Downloads</span><span class="link-span">${e.downloads}</span></p></li>
          </ul>
        </div>
      </li>`).join("")}const o={form:document.querySelector(".form"),btnSearch:document.querySelector(".btn-search"),imgList:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoad:document.querySelector(".btn-load")};let l,c="",n=1;const d=15;o.form.addEventListener("submit",async t=>{if(t.preventDefault(),c=t.target.elements.text.value.trim(),!c){i.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}g(),b(),o.imgList.innerHTML="",n=1;try{const e=await f(c,n,d);if(e.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"});return}o.imgList.innerHTML=h(e.hits),l?l.refresh():l=new x(".gallery-link",{captionsData:"alt",captionDelay:250}),e.totalHits>d&&L()}catch(e){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"}),console.error("Fetch error: ",e)}finally{y()}t.target.reset()});o.btnLoad.addEventListener("click",async()=>{n+=1,g(),b();try{const t=await f(c,n,d);o.imgList.insertAdjacentHTML("beforeend",h(t.hits)),l.refresh(),w(),n*d>=t.totalHits?i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}):L()}catch(t){i.error({title:"Error",message:"Sorry, there was an error loading more images. Please try again later.",position:"bottomRight"}),console.error("Fetch error: ",t)}finally{y()}});function g(){o.loader.classList.remove("hidden")}function y(){o.loader.classList.add("hidden")}function L(){o.btnLoad.classList.remove("hidden")}function b(){o.btnLoad.classList.add("hidden")}function w(){const t=o.imgList.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
